
[window]
decorations = "Full"
dynamic_padding = true

[general]
import = [
    # https://github.com/alacritty/alacritty-theme
    #"~/.config/alacritty/themes/themes/synthwave_84.toml"
    "~/.config/alacritty/themes/themes/tokyo-night.toml",
]

[font]
#normal.family = "Fira Code"
normal.family = "JetBrains Mono"
normal.style = "Regular"
#normal.features.ligatures = true
size = 12.0
#[window.dimensions]
#columns = 1916
#columns = 1000
#columns = 0
#lines = 1038
#lines = 1000
#lines = 0

#[font]
#size = 11.25
